"use client";

import { LanguageGlobe } from "@/components/menu/language-globe";
import { adminThemeChangeEvent, adminThemeStorageKey, ThemeToggle } from "@/components/menu/theme-toggle";
import { adminLocaleChangeEvent, adminLocaleStorageKey, useLocale } from "@/hooks/use-locale";
import type { Locale } from "@/types/models";

type AdminText = Record<string, string>;

const commonEn = {
  english: "English",
  arabic: "Arabic",
  kurdish: "Kurdish",
  englishName: "English name",
  arabicName: "Arabic name",
  kurdishName: "Kurdish name",
  englishDescription: "English description",
  arabicDescription: "Arabic description",
  kurdishDescription: "Kurdish description",
  save: "Save",
  saving: "Saving...",
  new: "New",
  edit: "Edit",
  duplicate: "Duplicate",
  preview: "Preview",
  delete: "Delete",
  cancel: "Cancel",
  active: "Active",
  inactive: "Inactive",
  all: "All",
  search: "Search",
  remove: "Remove",
  light: "Light",
  dark: "Dark",
  list: "List",
  grid: "Grid",
  flat: "Flat",
  outlined: "Outlined",
  elevated: "Elevated",
  compact: "Compact",
  expanded: "Expanded",
  category: "Category",
  noCategory: "No category"
};

const commonAr = {
  english: "الإنجليزية",
  arabic: "العربية",
  kurdish: "الكردية",
  englishName: "الاسم بالإنجليزية",
  arabicName: "الاسم بالعربية",
  kurdishName: "الاسم بالكردية",
  englishDescription: "الوصف بالإنجليزية",
  arabicDescription: "الوصف بالعربية",
  kurdishDescription: "الوصف بالكردية",
  save: "حفظ",
  saving: "جار الحفظ...",
  new: "جديد",
  edit: "تعديل",
  duplicate: "نسخ",
  preview: "معاينة",
  delete: "حذف",
  cancel: "إلغاء",
  active: "نشط",
  inactive: "غير نشط",
  all: "الكل",
  search: "بحث",
  remove: "إزالة",
  light: "فاتح",
  dark: "داكن",
  list: "قائمة",
  grid: "شبكة",
  flat: "مسطح",
  outlined: "بإطار",
  elevated: "مرتفع",
  compact: "مضغوط",
  expanded: "موسع",
  category: "القسم",
  noCategory: "بدون قسم"
};

const commonCkb = {
  english: "ئینگلیزی",
  arabic: "عەرەبی",
  kurdish: "کوردی",
  englishName: "ناوی ئینگلیزی",
  arabicName: "ناوی عەرەبی",
  kurdishName: "ناوی کوردی",
  englishDescription: "وەسفی ئینگلیزی",
  arabicDescription: "وەسفی عەرەبی",
  kurdishDescription: "وەسفی کوردی",
  save: "پاشەکەوت",
  saving: "پاشەکەوتکردن...",
  new: "نوێ",
  edit: "دەستکاری",
  duplicate: "کۆپی",
  preview: "پێشبینین",
  delete: "سڕینەوە",
  cancel: "هەڵوەشاندنەوە",
  active: "چالاک",
  inactive: "ناچالاک",
  all: "هەموو",
  search: "گەڕان",
  remove: "لابردن",
  light: "ڕووناک",
  dark: "تاریک",
  list: "لیست",
  grid: "تۆڕ",
  flat: "سادە",
  outlined: "چوارچێوەدار",
  elevated: "بەرزکراوە",
  compact: "کورت",
  expanded: "فراوان",
  category: "بەش",
  noCategory: "بێ بەش"
};

export const adminText: Record<Locale, AdminText> = {
  en: {
    ...commonEn,
    brand: "Stone Cafe Admin",
    dashboard: "Dashboard",
    categories: "Categories",
    menuItems: "Menu Items",
    pos: "POS",
    qrCode: "QR Code",
    settings: "Settings",
    logout: "Logout",
    adminProfile: "Admin profile",
    employeeSettings: "Employee settings",
    comingSoon: "Coming soon",
    accountSettings: "Account",
    firebaseRequiredTitle: "Firebase configuration required",
    firebaseRequiredDescription:
      "Admin pages require Firebase Authentication and Firestore. Add the values in `.env.local`, create an approved /adminProfiles/uid document, then restart the dev server.",
    viewPublicMenu: "View public menu",
    checkingSession: "Checking admin session...",
    redirecting: "Redirecting...",
    loginTitle: "Admin Login",
    loginDescription: "Use an approved Firebase admin account. Public registration is disabled.",
    missingFirebase: "Firebase client environment variables are missing. Add `.env.local` before signing in.",
    email: "Email",
    password: "Password",
    showPassword: "Show or hide password",
    enterEmailFirst: "Enter your email first.",
    resetSent: "Password reset email sent.",
    resetFailed: "Password reset failed.",
    loginFailed: "Login failed.",
    signingIn: "Signing in...",
    signIn: "Sign in",
    forgotPassword: "Forgot password",
    invalidCredential: "Email or password is incorrect.",
    tooManyRequests: "Too many attempts. Try again later.",
    authFailed: "Authentication failed. Check your details and try again.",
    dashboardDescription: "Menu overview and quick actions.",
    totalCategories: "Total categories",
    activeCategories: "Active categories",
    totalMenuItems: "Total menu items",
    availableItems: "Available items",
    soldOutItems: "Sold-out items",
    missingTranslations: "Missing translations",
    missingImages: "Missing images",
    addCategory: "Add Category",
    addMenuItem: "Add Menu Item",
    showQrCode: "Show QR Code",
    categoryDescription: "Create, edit, activate, deactivate, search, filter, and reorder categories.",
    categorySaved: "Category saved.",
    saveCategory: "Save category",
    searchCategories: "Search categories",
    displayOrder: "Display order",
    slug: "Slug",
    order: "Order",
    deleteCategory: "Delete category",
    categoryHasItems: "This category contains {count} menu item(s). Move them before deleting.",
    categoryHasNoItems: "This category has no menu items.",
    chooseDestinationCategory: "Choose destination category",
    menuItem: "Menu Item",
    menuItemDescription: "Create, edit, delete, filter, and manage item status.",
    posDescription: "Open tables, add menu items, calculate totals and discounts, and print compact receipts.",
    table: "Table",
    tables: "Tables",
    indoor: "Indoor",
    outdoor: "Outdoor",
    indoorTable: "Indoor table",
    outdoorTable: "Outdoor table",
    indoorTables: "Indoor tables",
    outdoorTables: "Outdoor tables",
    tableTools: "Table tools",
    tableName: "Table name",
    tableArea: "Table area",
    editTable: "Edit table",
    addTable: "Add table",
    addIndoorTable: "Add indoor table",
    addOutdoorTable: "Add outdoor table",
    removeTable: "Remove table",
    saveTable: "Save table",
    noTablesInArea: "No tables in this area.",
    moveUp: "Move up",
    moveDown: "Move down",
    menuPicker: "Menu picker",
    tapItemsToAdd: "Tap an item to add it to the selected table.",
    orderSummary: "Order summary",
    noItemsOnTable: "No items on this table.",
    subtotal: "Subtotal",
    discount: "Discount",
    amountDiscount: "Amount",
    percentDiscount: "Percent",
    total: "Total",
    moveOrder: "Move order",
    moveOrderToTable: "Move order to table",
    noOpenTables: "No open tables available.",
    occupied: "Occupied",
    completeOrder: "Complete order",
    clearTable: "Clear table",
    printInvoice: "Print invoice",
    receipt: "Receipt",
    qty: "Qty",
    tableSaved: "Table saved.",
    tableRemoved: "Table removed.",
    targetTableOccupied: "That table already has an order.",
    orderMoved: "Order moved.",
    orderCompleted: "Order completed and saved.",
    menuItemSaved: "Menu item saved.",
    savingItem: "Saving {name}...",
    menuItemSavedNamed: "{name} saved.",
    imageUploadInProgress: "Wait for the image upload to finish before saving.",
    addNewMenuItem: "Add a new item to the menu",
    saveItem: "Save item",
    chooseCategory: "Choose category",
    basePrice: "Base price",
    discountPrice: "Discount price",
    currency: "Currency",
    preparationMinutes: "Preparation minutes",
    calories: "Calories",
    spicyLevel: "Spicy level",
    tags: "Tags",
    allergens: "Allergens",
    dietaryLabels: "Dietary labels",
    englishIngredients: "English ingredients",
    arabicIngredients: "Arabic ingredients",
    kurdishIngredients: "Kurdish ingredients",
    tagsPlaceholder: "coffee, cold",
    allergensPlaceholder: "Dairy, nuts",
    dietaryLabelsPlaceholder: "vegetarian, sugar-free",
    available: "Available",
    soldOut: "Sold out",
    featured: "Featured",
    popular: "Popular",
    isNew: "New",
    itemImage: "Item image",
    variants: "Variants",
    addVariant: "Add variant",
    price: "Price",
    searchItems: "Search items",
    allCategories: "All categories",
    allStatuses: "All statuses",
    deleteItemConfirm: "Delete {name}?",
    settingsDescription: "Branding, menu behavior, appearance, and admin password.",
    generalSettings: "General Settings",
    restaurantNameEnglish: "Restaurant name English",
    restaurantNameArabic: "Restaurant name Arabic",
    restaurantNameKurdish: "Restaurant name Kurdish",
    phone: "Phone",
    whatsapp: "WhatsApp",
    address: "Address",
    googleMapsUrl: "Google Maps URL",
    logo: "Logo",
    coverImage: "Cover image",
    defaultLanguage: "Default language",
    defaultCurrency: "Default currency",
    menuSettings: "Menu Settings",
    showImages: "Show images",
    showPrices: "Show prices",
    showCalories: "Show calories",
    showIngredients: "Show ingredients",
    showAllergens: "Show allergens",
    showSoldOutItems: "Show sold-out items",
    enableSearch: "Enable search",
    enableFilters: "Enable filters",
    enableDarkMode: "Enable dark mode",
    appearanceSettings: "Appearance Settings",
    primaryColor: "Primary color",
    secondaryColor: "Secondary color",
    borderRadius: "Border radius",
    defaultTheme: "Default theme",
    cardStyle: "Card style",
    headerLayout: "Header layout",
    menuLayout: "Menu layout",
    saveSettings: "Save settings",
    settingsSaved: "Settings saved.",
    settingsSaveFailed: "Settings could not be saved.",
    adminPassword: "Admin Password",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    changePassword: "Change password",
    sendForgotPasswordEmail: "Send forgot-password email",
    passwordsMustMatch: "New passwords must match.",
    passwordRequirements: "Password must be at least 8 characters and include uppercase, lowercase, and a number.",
    authExpired: "Authentication expired. Sign in again.",
    passwordChanged: "Password changed.",
    passwordChangeFailed: "Password change failed.",
    qrDesign: "QR Design",
    menuUrl: "Menu URL",
    foregroundColor: "Foreground color",
    backgroundColor: "Background color",
    poorQrContrast: "Selected colors have poor contrast and may make the QR hard to scan.",
    includeLogo: "Include logo",
    titleEnglish: "Title English",
    titleArabic: "Title Arabic",
    titleKurdish: "Title Kurdish",
    reset: "Reset",
    hide: "Hide",
    show: "Show",
    mainMenuQrCode: "Main Menu QR Code",
    qrDescription: "One printable and copyable QR code for `/menu`. No table QR codes are generated.",
    menuQrCode: "Menu QR code",
    copyUrl: "Copy URL",
    copyQr: "Copy QR",
    print: "Print",
    printPage: "Print page",
    testLink: "Test link",
    qrSettingsSaved: "QR settings saved.",
    qrImageCopied: "QR image copied to clipboard.",
    qrImageUnsupported: "Image clipboard is unsupported, so the menu URL was copied.",
    qrImageCopyFailed: "QR image copy failed, so the menu URL was copied.",
    menuUrlCopied: "Menu URL copied.",
    uploadImage: "Upload image",
    removeImage: "Remove image",
    rollbackImage: "Restore previous image",
    uploading: "Uploading {progress}%",
    configureStorage: "Configure Supabase Storage to enable uploads.",
    imageUploadFailed: "Image upload failed.",
    invalidImageType: "Use a JPG, PNG, or WebP image.",
    imageTooLarge: "Images must be 5 MB or smaller.",
    englishRequired: "English is required.",
    arabicRequired: "Arabic is required.",
    kurdishRequired: "Kurdish is required.",
    slugRequired: "Slug is required.",
    categoryRequired: "Category is required."
  },
  ar: {
    ...commonAr,
    brand: "إدارة قائمة ستون كافيه",
    dashboard: "لوحة التحكم",
    categories: "الأقسام",
    menuItems: "عناصر القائمة",
    pos: "نقطة البيع",
    qrCode: "رمز QR",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    adminProfile: "ملف الإدارة",
    employeeSettings: "إعدادات الموظفين",
    comingSoon: "قريبا",
    accountSettings: "الحساب",
    firebaseRequiredTitle: "إعدادات Firebase مطلوبة",
    firebaseRequiredDescription:
      "صفحات الإدارة تحتاج إلى Firebase Authentication و Firestore. أضف القيم في `.env.local`، وأنشئ مستند /adminProfiles/uid معتمد، ثم أعد تشغيل خادم التطوير.",
    viewPublicMenu: "عرض القائمة العامة",
    checkingSession: "جار التحقق من جلسة الإدارة...",
    redirecting: "جار التحويل...",
    loginTitle: "تسجيل دخول الإدارة",
    loginDescription: "استخدم حساب Firebase إداري معتمد. التسجيل العام غير مفعل.",
    missingFirebase: "متغيرات بيئة Firebase الخاصة بالعميل غير موجودة. أضف `.env.local` قبل تسجيل الدخول.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    showPassword: "إظهار أو إخفاء كلمة المرور",
    enterEmailFirst: "أدخل بريدك الإلكتروني أولا.",
    resetSent: "تم إرسال بريد إعادة تعيين كلمة المرور.",
    resetFailed: "فشلت إعادة تعيين كلمة المرور.",
    loginFailed: "فشل تسجيل الدخول.",
    signingIn: "جار تسجيل الدخول...",
    signIn: "تسجيل الدخول",
    forgotPassword: "نسيت كلمة المرور",
    invalidCredential: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    tooManyRequests: "محاولات كثيرة. حاول لاحقا.",
    authFailed: "فشلت المصادقة. تحقق من البيانات وحاول مرة أخرى.",
    dashboardDescription: "نظرة عامة على القائمة وإجراءات سريعة.",
    totalCategories: "إجمالي الأقسام",
    activeCategories: "الأقسام النشطة",
    totalMenuItems: "إجمالي عناصر القائمة",
    availableItems: "العناصر المتاحة",
    soldOutItems: "العناصر النافدة",
    missingTranslations: "ترجمات ناقصة",
    missingImages: "صور ناقصة",
    addCategory: "إضافة قسم",
    addMenuItem: "إضافة عنصر",
    showQrCode: "عرض رمز QR",
    categoryDescription: "أنشئ وعدل وفعل وعطل وابحث وصفي ورتب الأقسام.",
    categorySaved: "تم حفظ القسم.",
    saveCategory: "حفظ القسم",
    searchCategories: "بحث في الأقسام",
    displayOrder: "ترتيب العرض",
    slug: "الرابط المختصر",
    order: "الترتيب",
    deleteCategory: "حذف القسم",
    categoryHasItems: "هذا القسم يحتوي على {count} عنصر. انقلها قبل الحذف.",
    categoryHasNoItems: "هذا القسم لا يحتوي على عناصر.",
    chooseDestinationCategory: "اختر قسم الوجهة",
    menuItem: "عنصر القائمة",
    menuItemDescription: "أنشئ وعدل واحذف وصفي وأدر حالة العناصر.",
    posDescription: "افتح الطاولات، أضف عناصر القائمة، احسب الإجمالي والخصومات، واطبع إيصالات صغيرة.",
    table: "طاولة",
    tables: "الطاولات",
    indoor: "داخلي",
    outdoor: "خارجي",
    indoorTable: "طاولة داخلية",
    outdoorTable: "طاولة خارجية",
    indoorTables: "الطاولات الداخلية",
    outdoorTables: "الطاولات الخارجية",
    tableTools: "أدوات الطاولات",
    tableName: "اسم الطاولة",
    tableArea: "مكان الطاولة",
    editTable: "تعديل الطاولة",
    addTable: "إضافة طاولة",
    addIndoorTable: "إضافة طاولة داخلية",
    addOutdoorTable: "إضافة طاولة خارجية",
    removeTable: "إزالة الطاولة",
    saveTable: "حفظ الطاولة",
    noTablesInArea: "لا توجد طاولات في هذا المكان.",
    moveUp: "تحريك للأعلى",
    moveDown: "تحريك للأسفل",
    menuPicker: "اختيار العناصر",
    tapItemsToAdd: "اضغط على عنصر لإضافته إلى الطاولة المحددة.",
    orderSummary: "ملخص الطلب",
    noItemsOnTable: "لا توجد عناصر على هذه الطاولة.",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    amountDiscount: "مبلغ",
    percentDiscount: "نسبة",
    total: "الإجمالي",
    moveOrder: "نقل الطلب",
    moveOrderToTable: "نقل الطلب إلى طاولة",
    noOpenTables: "لا توجد طاولات فارغة متاحة.",
    occupied: "مشغولة",
    completeOrder: "إكمال الطلب",
    clearTable: "تفريغ الطاولة",
    printInvoice: "طباعة الفاتورة",
    receipt: "إيصال",
    qty: "الكمية",
    tableSaved: "تم حفظ الطاولة.",
    tableRemoved: "تمت إزالة الطاولة.",
    targetTableOccupied: "هذه الطاولة لديها طلب بالفعل.",
    orderMoved: "تم نقل الطلب.",
    orderCompleted: "تم إكمال الطلب وحفظه.",
    menuItemSaved: "تم حفظ عنصر القائمة.",
    savingItem: "جار حفظ {name}...",
    menuItemSavedNamed: "تم حفظ {name}.",
    imageUploadInProgress: "انتظر انتهاء رفع الصورة قبل الحفظ.",
    addNewMenuItem: "إضافة عنصر جديد إلى القائمة",
    saveItem: "حفظ العنصر",
    chooseCategory: "اختر قسما",
    basePrice: "السعر الأساسي",
    discountPrice: "سعر الخصم",
    currency: "العملة",
    preparationMinutes: "دقائق التحضير",
    calories: "السعرات",
    spicyLevel: "درجة الحار",
    tags: "الوسوم",
    allergens: "مسببات الحساسية",
    dietaryLabels: "التصنيفات الغذائية",
    englishIngredients: "المكونات بالإنجليزية",
    arabicIngredients: "المكونات بالعربية",
    kurdishIngredients: "المكونات بالكردية",
    tagsPlaceholder: "قهوة، بارد",
    allergensPlaceholder: "ألبان، مكسرات",
    dietaryLabelsPlaceholder: "نباتي، بدون سكر",
    available: "متاح",
    soldOut: "نافد",
    featured: "مميز",
    popular: "شائع",
    isNew: "جديد",
    itemImage: "صورة العنصر",
    variants: "الخيارات",
    addVariant: "إضافة خيار",
    price: "السعر",
    searchItems: "بحث في العناصر",
    allCategories: "كل الأقسام",
    allStatuses: "كل الحالات",
    deleteItemConfirm: "حذف {name}؟",
    settingsDescription: "العلامة التجارية وسلوك القائمة والمظهر وكلمة مرور الإدارة.",
    generalSettings: "الإعدادات العامة",
    restaurantNameEnglish: "اسم المطعم بالإنجليزية",
    restaurantNameArabic: "اسم المطعم بالعربية",
    restaurantNameKurdish: "اسم المطعم بالكردية",
    phone: "الهاتف",
    whatsapp: "واتساب",
    address: "العنوان",
    googleMapsUrl: "رابط خرائط Google",
    logo: "الشعار",
    coverImage: "صورة الغلاف",
    defaultLanguage: "اللغة الافتراضية",
    defaultCurrency: "العملة الافتراضية",
    menuSettings: "إعدادات القائمة",
    showImages: "إظهار الصور",
    showPrices: "إظهار الأسعار",
    showCalories: "إظهار السعرات",
    showIngredients: "إظهار المكونات",
    showAllergens: "إظهار مسببات الحساسية",
    showSoldOutItems: "إظهار العناصر النافدة",
    enableSearch: "تفعيل البحث",
    enableFilters: "تفعيل الفلاتر",
    enableDarkMode: "تفعيل الوضع الداكن",
    appearanceSettings: "إعدادات المظهر",
    primaryColor: "اللون الأساسي",
    secondaryColor: "اللون الثانوي",
    borderRadius: "استدارة الحواف",
    defaultTheme: "السمة الافتراضية",
    cardStyle: "نمط البطاقة",
    headerLayout: "تخطيط الرأس",
    menuLayout: "تخطيط القائمة",
    saveSettings: "حفظ الإعدادات",
    settingsSaved: "تم حفظ الإعدادات.",
    settingsSaveFailed: "تعذر حفظ الإعدادات.",
    adminPassword: "كلمة مرور الإدارة",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    changePassword: "تغيير كلمة المرور",
    sendForgotPasswordEmail: "إرسال بريد استعادة كلمة المرور",
    passwordsMustMatch: "كلمات المرور الجديدة يجب أن تتطابق.",
    passwordRequirements: "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي على حرف كبير وصغير ورقم.",
    authExpired: "انتهت المصادقة. سجل الدخول مرة أخرى.",
    passwordChanged: "تم تغيير كلمة المرور.",
    passwordChangeFailed: "فشل تغيير كلمة المرور.",
    qrDesign: "تصميم QR",
    menuUrl: "رابط القائمة",
    foregroundColor: "لون المقدمة",
    backgroundColor: "لون الخلفية",
    poorQrContrast: "الألوان المختارة ضعيفة التباين وقد تجعل QR صعب المسح.",
    includeLogo: "تضمين الشعار",
    titleEnglish: "العنوان بالإنجليزية",
    titleArabic: "العنوان بالعربية",
    titleKurdish: "العنوان بالكردية",
    reset: "إعادة ضبط",
    hide: "إخفاء",
    show: "إظهار",
    mainMenuQrCode: "رمز QR للقائمة الرئيسية",
    qrDescription: "رمز QR واحد قابل للطباعة والنسخ لـ `/menu`. لا يتم إنشاء رموز للطاولات.",
    menuQrCode: "رمز QR للقائمة",
    copyUrl: "نسخ الرابط",
    copyQr: "نسخ QR",
    print: "طباعة",
    printPage: "صفحة الطباعة",
    testLink: "اختبار الرابط",
    qrSettingsSaved: "تم حفظ إعدادات QR.",
    qrImageCopied: "تم نسخ صورة QR إلى الحافظة.",
    qrImageUnsupported: "نسخ الصورة غير مدعوم، لذلك تم نسخ رابط القائمة.",
    qrImageCopyFailed: "فشل نسخ صورة QR، لذلك تم نسخ رابط القائمة.",
    menuUrlCopied: "تم نسخ رابط القائمة.",
    uploadImage: "رفع صورة",
    removeImage: "إزالة الصورة",
    rollbackImage: "استعادة الصورة السابقة",
    uploading: "جار الرفع {progress}%",
    configureStorage: "قم بإعداد Supabase Storage لتفعيل الرفع.",
    imageUploadFailed: "فشل رفع الصورة.",
    invalidImageType: "استخدم صورة JPG أو PNG أو WebP.",
    imageTooLarge: "يجب أن تكون الصور 5 MB أو أقل.",
    englishRequired: "الإنجليزية مطلوبة.",
    arabicRequired: "العربية مطلوبة.",
    kurdishRequired: "الكردية مطلوبة.",
    slugRequired: "الرابط المختصر مطلوب.",
    categoryRequired: "القسم مطلوب."
  },
  ckb: {
    ...commonCkb,
    brand: "بەڕێوەبردنی مینیوی ستۆن کافێ",
    dashboard: "داشبۆرد",
    categories: "بەشەکان",
    menuItems: "بابەتەکانی مینیو",
    pos: "POS",
    qrCode: "کۆدی QR",
    settings: "ڕێکخستنەکان",
    logout: "چوونەدەرەوە",
    adminProfile: "پرۆفایلی بەڕێوەبردن",
    employeeSettings: "ڕێکخستنی کارمەندان",
    comingSoon: "بەم زووانە",
    accountSettings: "هەژمار",
    firebaseRequiredTitle: "ڕێکخستنی Firebase پێویستە",
    firebaseRequiredDescription:
      "پەڕەکانی بەڕێوەبردن پێویستیان بە Firebase Authentication و Firestore هەیە. نرخەکان لە `.env.local` زیاد بکە، دۆکیومێنتی /adminProfiles/uid ی پەسەند دروست بکە، پاشان سێرڤەری گەشەپێدان دووبارە پێبکە.",
    viewPublicMenu: "بینینی مینیوی گشتی",
    checkingSession: "پشکنینی دانیشتنی بەڕێوەبردن...",
    redirecting: "گواستنەوە...",
    loginTitle: "چوونەژوورەوەی بەڕێوەبردن",
    loginDescription: "هەژمارێکی Firebase ی بەڕێوەبەری پەسەندکراو بەکاربهێنە. تۆمارکردنی گشتی ناچالاکە.",
    missingFirebase: "گۆڕاوەکانی ژینگەی Firebase ی کلایەنت نییە. پێش چوونەژوورەوە `.env.local` زیاد بکە.",
    email: "ئیمەیل",
    password: "وشەی نهێنی",
    showPassword: "نیشاندان یان شاردنەوەی وشەی نهێنی",
    enterEmailFirst: "سەرەتا ئیمەیلەکەت بنووسە.",
    resetSent: "ئیمەیلی نوێکردنەوەی وشەی نهێنی نێردرا.",
    resetFailed: "نوێکردنەوەی وشەی نهێنی سەرکەوتوو نەبوو.",
    loginFailed: "چوونەژوورەوە سەرکەوتوو نەبوو.",
    signingIn: "چوونەژوورەوە...",
    signIn: "چوونەژوورەوە",
    forgotPassword: "وشەی نهێنیت لەبیر کردووە",
    invalidCredential: "ئیمەیل یان وشەی نهێنی هەڵەیە.",
    tooManyRequests: "هەوڵی زۆر دراوە. دواتر هەوڵ بدەوە.",
    authFailed: "پەسەندکردن سەرکەوتوو نەبوو. زانیارییەکان بپشکنە و دووبارە هەوڵ بدەوە.",
    dashboardDescription: "پوختەی مینیو و کردارە خێراکان.",
    totalCategories: "کۆی بەشەکان",
    activeCategories: "بەشە چالاکەکان",
    totalMenuItems: "کۆی بابەتەکانی مینیو",
    availableItems: "بابەتە بەردەستەکان",
    soldOutItems: "بابەتە تەواوبووەکان",
    missingTranslations: "وەرگێڕانی کەم",
    missingImages: "وێنەی کەم",
    addCategory: "زیادکردنی بەش",
    addMenuItem: "زیادکردنی بابەت",
    showQrCode: "نیشاندانی کۆدی QR",
    categoryDescription: "بەشەکان دروست بکە، دەستکاری بکە، چالاک/ناچالاک بکە، بگەڕێ، فلتەر بکە و ڕیزبەندی بکە.",
    categorySaved: "بەشەکە پاشەکەوت کرا.",
    saveCategory: "پاشەکەوتی بەش",
    searchCategories: "گەڕان لە بەشەکان",
    displayOrder: "ڕیزبەندی نیشاندان",
    slug: "سلەگ",
    order: "ڕیز",
    deleteCategory: "سڕینەوەی بەش",
    categoryHasItems: "ئەم بەشە {count} بابەتی مینیوی تێدایە. پێش سڕینەوە بیانوگوازەوە.",
    categoryHasNoItems: "ئەم بەشە هیچ بابەتێکی مینیوی تێدا نییە.",
    chooseDestinationCategory: "بەشی مەبەست هەڵبژێرە",
    menuItem: "بابەتی مینیو",
    menuItemDescription: "بابەت دروست بکە، دەستکاری بکە، بسڕەوە، فلتەر بکە و دۆخی بابەت بەڕێوەبەرە.",
    posDescription: "مێزەکان بکەرەوە، بابەت زیاد بکە، کۆی گشتی و داشکاندن هەژمار بکە و پسووڵەی بچووک چاپ بکە.",
    table: "مێز",
    tables: "مێزەکان",
    indoor: "ناوەوە",
    outdoor: "دەرەوە",
    indoorTable: "مێزی ناوەوە",
    outdoorTable: "مێزی دەرەوە",
    indoorTables: "مێزەکانی ناوەوە",
    outdoorTables: "مێزەکانی دەرەوە",
    tableTools: "ئامرازەکانی مێز",
    tableName: "ناوی مێز",
    tableArea: "شوێنی مێز",
    editTable: "دەستکاریکردنی مێز",
    addTable: "زیادکردنی مێز",
    addIndoorTable: "زیادکردنی مێزی ناوەوە",
    addOutdoorTable: "زیادکردنی مێزی دەرەوە",
    removeTable: "لابردنی مێز",
    saveTable: "پاشەکەوتی مێز",
    noTablesInArea: "هیچ مێزێک لەم شوێنەدا نییە.",
    moveUp: "بەرەو سەرەوە",
    moveDown: "بەرەو خوارەوە",
    menuPicker: "هەڵبژاردنی مینیو",
    tapItemsToAdd: "کرتە لە بابەت بکە بۆ زیادکردنی بۆ مێزی هەڵبژێردراو.",
    orderSummary: "پوختەی داواکاری",
    noItemsOnTable: "هیچ بابەتێک لەم مێزەدا نییە.",
    subtotal: "کۆی لاوەکی",
    discount: "داشکاندن",
    amountDiscount: "بڕ",
    percentDiscount: "لەسەدا",
    total: "کۆی گشتی",
    moveOrder: "گواستنەوەی داواکاری",
    moveOrderToTable: "گواستنەوەی داواکاری بۆ مێز",
    noOpenTables: "هیچ مێزێکی بەتاڵ بەردەست نییە.",
    occupied: "گیراوە",
    completeOrder: "تەواوکردنی داواکاری",
    clearTable: "پاککردنەوەی مێز",
    printInvoice: "چاپکردنی پسووڵە",
    receipt: "پسووڵە",
    qty: "دانە",
    tableSaved: "مێزەکە پاشەکەوت کرا.",
    tableRemoved: "مێزەکە لابرا.",
    targetTableOccupied: "ئەم مێزە پێشتر داواکاریی لەسەرە.",
    orderMoved: "داواکارییەکە گوازرایەوە.",
    orderCompleted: "داواکارییەکە تەواو و پاشەکەوت کرا.",
    menuItemSaved: "بابەتی مینیو پاشەکەوت کرا.",
    savingItem: "پاشەکەوتکردنی {name}...",
    menuItemSavedNamed: "{name} پاشەکەوت کرا.",
    imageUploadInProgress: "چاوەڕێ بکە بارکردنی وێنە تەواو بێت پێش پاشەکەوتکردن.",
    addNewMenuItem: "زیادکردنی بابەتی نوێ بۆ مینیو",
    saveItem: "پاشەکەوتی بابەت",
    chooseCategory: "بەش هەڵبژێرە",
    basePrice: "نرخی بنەڕەتی",
    discountPrice: "نرخی داشکاندن",
    currency: "دراو",
    preparationMinutes: "خولەکەکانی ئامادەکردن",
    calories: "کالۆری",
    spicyLevel: "ئاستی تیژی",
    tags: "تاگەکان",
    allergens: "هۆکارەکانی هەستیاری",
    dietaryLabels: "ناسێنەری خواردن",
    englishIngredients: "پێکهاتە بە ئینگلیزی",
    arabicIngredients: "پێکهاتە بە عەرەبی",
    kurdishIngredients: "پێکهاتە بە کوردی",
    tagsPlaceholder: "قاوە، سارد",
    allergensPlaceholder: "شیرەمەنی، گوێز",
    dietaryLabelsPlaceholder: "ڕووەکی، بێ شەکر",
    available: "بەردەست",
    soldOut: "تەواوبوو",
    featured: "تایبەت",
    popular: "بەناوبانگ",
    isNew: "نوێ",
    itemImage: "وێنەی بابەت",
    variants: "جۆرەکان",
    addVariant: "زیادکردنی جۆر",
    price: "نرخ",
    searchItems: "گەڕان لە بابەتەکان",
    allCategories: "هەموو بەشەکان",
    allStatuses: "هەموو دۆخەکان",
    deleteItemConfirm: "ئایا {name} بسڕدرێتەوە؟",
    settingsDescription: "براندینگ، ڕەفتاری مینیو، دەرکەوتن و وشەی نهێنی بەڕێوەبردن.",
    generalSettings: "ڕێکخستنە گشتییەکان",
    restaurantNameEnglish: "ناوی چێشتخانە بە ئینگلیزی",
    restaurantNameArabic: "ناوی چێشتخانە بە عەرەبی",
    restaurantNameKurdish: "ناوی چێشتخانە بە کوردی",
    phone: "تەلەفۆن",
    whatsapp: "واتساپ",
    address: "ناونیشان",
    googleMapsUrl: "لینکی Google Maps",
    logo: "لۆگۆ",
    coverImage: "وێنەی سەرەوە",
    defaultLanguage: "زمانی بنەڕەت",
    defaultCurrency: "دراوی بنەڕەت",
    menuSettings: "ڕێکخستنەکانی مینیو",
    showImages: "نیشاندانی وێنەکان",
    showPrices: "نیشاندانی نرخەکان",
    showCalories: "نیشاندانی کالۆری",
    showIngredients: "نیشاندانی پێکهاتەکان",
    showAllergens: "نیشاندانی هۆکارەکانی هەستیاری",
    showSoldOutItems: "نیشاندانی بابەتە تەواوبووەکان",
    enableSearch: "چالاککردنی گەڕان",
    enableFilters: "چالاککردنی فلتەرەکان",
    enableDarkMode: "چالاککردنی دۆخی تاریک",
    appearanceSettings: "ڕێکخستنەکانی دەرکەوتن",
    primaryColor: "ڕەنگی سەرەکی",
    secondaryColor: "ڕەنگی دووەم",
    borderRadius: "سووڕی گۆشەکان",
    defaultTheme: "ڕووکاری بنەڕەت",
    cardStyle: "شێوازی کارت",
    headerLayout: "ڕێکخستنی سەرپەڕە",
    menuLayout: "ڕێکخستنی مینیو",
    saveSettings: "پاشەکەوتی ڕێکخستنەکان",
    settingsSaved: "ڕێکخستنەکان پاشەکەوت کران.",
    settingsSaveFailed: "ڕێکخستنەکان پاشەکەوت نەکران.",
    adminPassword: "وشەی نهێنی بەڕێوەبردن",
    currentPassword: "وشەی نهێنی ئێستا",
    newPassword: "وشەی نهێنی نوێ",
    confirmNewPassword: "دڵنیایی وشەی نهێنی نوێ",
    changePassword: "گۆڕینی وشەی نهێنی",
    sendForgotPasswordEmail: "ناردنی ئیمەیلی لەبیرکردنی وشەی نهێنی",
    passwordsMustMatch: "وشە نهێنییە نوێیەکان دەبێت وەک یەک بن.",
    passwordRequirements: "وشەی نهێنی دەبێت لانیکەم ٨ پیت بێت و پیتی گەورە، بچووک و ژمارەی تێدا بێت.",
    authExpired: "پەسەندکردن کۆتایی هاتووە. دووبارە بچۆ ژوورەوە.",
    passwordChanged: "وشەی نهێنی گۆڕدرا.",
    passwordChangeFailed: "گۆڕینی وشەی نهێنی سەرکەوتوو نەبوو.",
    qrDesign: "دیزاینی QR",
    menuUrl: "لینکی مینیو",
    foregroundColor: "ڕەنگی پێشەوە",
    backgroundColor: "ڕەنگی پاشەوە",
    poorQrContrast: "ڕەنگە هەڵبژێردراوەکان جیاوازی کەمیان هەیە و لەوانەیە QR بە ئاسانی سکان نەکرێت.",
    includeLogo: "لەخۆگرتنی لۆگۆ",
    titleEnglish: "ناونیشانی ئینگلیزی",
    titleArabic: "ناونیشانی عەرەبی",
    titleKurdish: "ناونیشانی کوردی",
    reset: "گەڕاندنەوە",
    hide: "شاردنەوە",
    show: "نیشاندان",
    mainMenuQrCode: "کۆدی QR ی مینیوی سەرەکی",
    qrDescription: "یەک کۆدی QR ی چاپکراو و کۆپیکراو بۆ `/menu`. کۆدی مێز دروست ناکرێت.",
    menuQrCode: "کۆدی QR ی مینیو",
    copyUrl: "کۆپیکردنی لینک",
    copyQr: "کۆپیکردنی QR",
    print: "چاپ",
    printPage: "پەڕەی چاپ",
    testLink: "تاقیکردنەوەی لینک",
    qrSettingsSaved: "ڕێکخستنەکانی QR پاشەکەوت کران.",
    qrImageCopied: "وێنەی QR بۆ کلیپبۆرد کۆپی کرا.",
    qrImageUnsupported: "کۆپیکردنی وێنە پشتگیری ناکرێت، بۆیە لینکی مینیو کۆپی کرا.",
    qrImageCopyFailed: "کۆپیکردنی وێنەی QR سەرکەوتوو نەبوو، بۆیە لینکی مینیو کۆپی کرا.",
    menuUrlCopied: "لینکی مینیو کۆپی کرا.",
    uploadImage: "بارکردنی وێنە",
    removeImage: "لابردنی وێنە",
    rollbackImage: "گەڕاندنەوەی وێنەی پێشوو",
    uploading: "بارکردن {progress}%",
    configureStorage: "Supabase Storage ڕێکبخە بۆ چالاککردنی بارکردن.",
    imageUploadFailed: "بارکردنی وێنە سەرکەوتوو نەبوو.",
    invalidImageType: "وێنەی JPG، PNG یان WebP بەکاربهێنە.",
    imageTooLarge: "وێنەکان دەبێت ٥ MB یان بچووکتر بن.",
    englishRequired: "ئینگلیزی پێویستە.",
    arabicRequired: "عەرەبی پێویستە.",
    kurdishRequired: "کوردی پێویستە.",
    slugRequired: "سلەگ پێویستە.",
    categoryRequired: "بەش پێویستە."
  }
};

export function formatAdminText(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template);
}

export function adminErrorText(message: string | undefined, text: AdminText) {
  if (!message) return undefined;
  if (message.includes("English is required")) return text.englishRequired;
  if (message.includes("Arabic is required")) return text.arabicRequired;
  if (message.includes("Kurdish is required")) return text.kurdishRequired;
  if (message.includes("Slug is required")) return text.slugRequired;
  if (message.includes("Category is required")) return text.categoryRequired;
  if (message.includes("Use a JPG")) return text.invalidImageType;
  if (message.includes("5 MB")) return text.imageTooLarge;
  if (message.includes("Storage is not configured")) return text.configureStorage;
  return message;
}

export function useAdminLocale() {
  const { locale, setLocale, dir } = useLocale("ckb", {
    documentDirection: "ltr",
    storageKey: adminLocaleStorageKey,
    changeEvent: adminLocaleChangeEvent
  });
  return { locale, setLocale, dir, text: adminText[locale] };
}

export function AdminPreferences({ compact = false }: { compact?: boolean }) {
  const { locale, setLocale } = useAdminLocale();

  return (
    <div dir="ltr" className={compact ? "flex shrink-0 items-center gap-2" : "flex items-center gap-2"}>
      <LanguageGlobe locale={locale} onChange={setLocale} menuAlign="left" />
      <ThemeToggle storageKey={adminThemeStorageKey} changeEvent={adminThemeChangeEvent} />
    </div>
  );
}
